#!/bin/bash -eu

[ ! -v MANPAGER ] && export MANPAGER="less -R --use-color -Dd+y -Du+c"

shopt -s nullglob extglob

: ${repo:=sisyphus}
: ${arch:=$HOSTTYPE}

CACHE=$HOME/.cache/apt-man
PAGES=$CACHE/man-$repo-$arch

addtab=
wordsep='.*'
for opt; do
	shift
	case "$opt" in
		-p) addtab=$'\t' ;;
		-w|-x) wordsep='\b' ;&
		-*) set -- "$@" "$opt" ;;
		*) pat=$opt ;;
	esac
done

if [ -z "$(find "$PAGES" -type f -ctime -7 2>/dev/null)" ]; then
	mkdir -p "$CACHE"
	cat /ALT/"$repo"/{"$arch",noarch}/base/contents_index \
	| grep '^/usr/share/.*/man' > "$PAGES-"
	mv -f "$PAGES-" "$PAGES"
fi

label=$(grep "^/usr/share/.*/man.*$addtab$wordsep$pat" "$@" "$PAGES" \
	| fzf --height=~100%)
read file pkgname <<<$label
for arch in $arch noarch; do
	dir=/ALT/$repo/files/$arch/RPMS
	pkg=( "$dir"/"$pkgname"-+([^-])-alt*."$arch".rpm )
	if [ -v pkg ]; then
		exec rpmpeek "$pkg" man ".$file"
	fi
done
