#!/bin/bash
# Search API: https://docs.github.com/en/rest/search
# Another API: https://docs.github.com/en/rest/issues
# https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax
# https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

set -efu +o posix
fatal() { echo >&2 "! $*"; exit 1; }

  BRIGHT=$'\e[1m'
     RED=$'\e[31m'
   GREEN=$'\e[32m'
  YELLOW=$'\e[33m'
    BLUE=$'\e[34m'
 MAGENTA=$'\e[35m'
    CYAN=$'\e[36m'
   WHITE=$'\e[37m'
    NORM=$'\e[m'
export BRIGHT RED GREEN YELLOW BLUE MAGENTA CYAN WHITE NORM

unset date ref is state specfile
setx=
at=created
date_cmp='>='
for opt do
	shift
	arg=${opt#*=}
	# shellcheck disable=SC2209
	case "$opt" in
		--tag=*) ref=$arg ;;
		--date=*) date=$arg ;;
		=[[:digit:]]*) opt=${opt/=/-}; date_cmp='' ;&
		-[[:digit:]]*) date=$(date --date="$opt day" +%F) ;;
		--remote=*) remote=$arg ;;
		--updated) at=updated ;;
		--pr) is=pr ;;
		--issue | --issues) is=issue ;;
		--open) state=open ;;
		--closed) state=closed ;;
		-v) setx='set -x' ;;
		-*) fatal "Unknwon option: $opt" ;;
		*) set -- "$@" "$opt";;
	esac
done

cdup=$(git rev-parse --show-cdup)
# shellcheck disable=SC2030
guess_specfile() (
	# shellcheck disable=SC1091
	. gear-utils-sh-functions
	export disable_specsubst=1
	chdir_to_toplevel
	guess_specfile
	echo "$cdup$specfile"
)

if [ ! -v remote ]; then
	remote=$(git remote -v | grep -Po "https://github\.com/\S+" -m1 ||:)
fi
if [ -z "$remote" ]; then
	specfile=$(guess_specfile)
	remote=$(grep -i '^(Url|Vcs):.*github.com' "$specfile" ||:)
fi
[ -n "$remote" ] || fatal "GitHub url not found."
repo=${remote#*github.com/}
repo=${repo%/}
repo=${repo%.git}
[ -n "$repo" ] || fatal "Unknown GitHub repo."

# shellcheck disable=SC2166
if [ -v date ]; then
	echo >&2 "Using date from command line"
elif [ -v ref ]; then
	echo >&2 "Using committer date from tag"
	date=$(git log -1 --format=%cd --date=short "$ref")
elif [ -e "$cdup.gear-rules" -o -e "$cdup.gear/rules" ]; then
	[ -v specfile ] || specfile=$(guess_specfile)
	changelog_date=$(grep -A2 '%changelog' "$specfile" | grep -Po '(First import|Updated? to) \S+ \(\K\S+(?=\))')
	echo >&2 "Using update date from the latest %changelog entry"
	date=$changelog_date
fi
[ -v date ] || fatal "Specify date or a tag to get committer date from it."

q="repo:$repo $at:$date_cmp$date"
[ -v state ] && q+=" state:$state"
[ -v is ] && q+=" is:$is"

echo "Query is: $q"
Q=$(jq -sRr @uri <<<"$q")
[ -v LESS ] || export LESS=-MMXRF

tf="$HOME/.cache/bugs"
mkdir -p "$tf"
tf+="/${q//\//|}"
($setx; curl -sSf "https://api.github.com/search/issues?q=$Q&sort=created&per_page=99" -o "$tf")
jq -r '.items[] | [
	.number,
	(.created_at | fromdate | strftime("%F")),
	(.author_association | if . == "NONE" then "\u00A0" elif . == "CONTRIBUTOR" then "cn" else (gsub("(?i)[aeiou]"; "") | .[:2]) end),
	if (.user.login | length) > 8 then .user.login[0:7] + "…" else .user.login end,
	(if .pull_request? then if .pull_request.merged_at then "✅" else "⚡" end else "\u00A0" end),
	if .state == "open" then "\u00A0" else "✓" end,
	.comments,
	.title
] | @tsv' <"$tf" | column -t -s $'\t' |
sed -E \
	-e "s/([^e]bug|crash|error|regress|fail)/$BRIGHT$RED&$NORM/i" \
	-e "s/(fix)/$BRIGHT$GREEN&$NORM/i" \
	-e "s/(implement|add|sync)/$YELLOW&$NORM/i" \
	-e "s/(✅|✓)/$GREEN&$NORM/g" \
	-e "s/(🔄|⚪)/$BRIGHT$BLUE&$NORM/g" \
	-e "s/(⚡)/$YELLOW&$NORM/g" |
less
