#!/bin/bash
set -efu +o posix

fatal() { echo >&2 "${0##*/}: error: $*"; exit 1; }

  BRIGHT=$'\e[1m'
     RED=$'\e[31m'
   GREEN=$'\e[32m'
  YELLOW=$'\e[33m'
    BLUE=$'\e[34m'
 MAGENTA=$'\e[35m'
    CYAN=$'\e[36m'
   WHITE=$'\e[37m'
    NORM=$'\e[m'
export BRIGHT RED GREEN YELLOW BLUE MAGENTA CYAN WHITE NORM

br=$(git br --show-current)
repo=${br##*/}
flv=${br%%/*}
arch=x86_64
diffconfig_opts=()
dts=
fzf=
bb_opts=
for opt do
        shift
	arg=${opt#*=}
        case "$opt" in
		-32) arch=i586 ;;
		--flv=*) flv=$arg ;;
		--repo=*) repo=$arg ;;
		--arch=*) arch=$arg ;;
		--skip-bb) skip_bb=y ;;
		--dts) dts=--dts ;;
		--fzf) fzf=--fzf ;;
		--tag=* | --kflavour=*) bb_opts=$opt ;;
		-m) diffconfig_opts=("$opt") ;;
		-*) fatal "unknown option: $opt" ;;
                *) fatal "unknown argument: $opt" ;;
        esac
done

# shellcheck disable=SC2064
tmp=$(mktemp -d) && trap "rm -rf '$tmp'" 0

# shellcheck disable=SC2086
rpm_a=$(list-package $repo $arch $dts $fzf "kernel-image-$flv" --list-only)
bn_a=$(basename "$rpm_a")
date_a=$(date -r "$rpm_a" +%F)
f_a="$tmp/$bn_a"
kernel-config "$rpm_a" > "$f_a"
size_a=$(stat -c %s "$f_a")
echo >&2 "Compare with $rpm_a ($size_a bytes, $date_a)"

if [ ! -v skip_bb ]; then
	# shellcheck disable=SC2086
	gum spin --title="Building .config ($repo/$arch)..." -- bb --repo="$repo" --arch="$arch" $bb_opts --kconfig --no-log
	echo "Built .config for $repo/$arch"
fi
bn_b=".config"
f_b="$tmp/$bn_b"
hsh-get -q "$bn_b" --directory="$tmp"
size_b=$(stat -c %s "$f_b")
date_b=$(date -r "$f_b" +'%F %R')
echo >&2 "Compare with $bn_b ($size_b bytes, $date_b)"

(
	cd "$tmp"
	PATH="$HOME/linux/torvalds/scripts:$PATH"
	set -x
	diffconfig "${diffconfig_opts[@]}" "$bn_a" "$bn_b"
) | sed -e "s/\bm\b/$BRIGHT$GREEN&$NORM/g" \
	-e "s/\by\b/$BRIGHT$YELLOW&$NORM/g" \
	-e "s/\bn\b/$BRIGHT$RED&$NORM/g"
