#!/bin/bash
set -efu +o posix

fatal() { echo >&2 "${0##*/}: error: $*"; exit 1; }

  BRIGHT=$'\e[1m'
     RED=$'\e[31m'
   GREEN=$'\e[32m'
  YELLOW=$'\e[33m'
    BLUE=$'\e[34m'
 MAGENTA=$'\e[35m'
    CYAN=$'\e[36m'
   WHITE=$'\e[37m'
    NORM=$'\e[m'
export BRIGHT RED GREEN YELLOW BLUE MAGENTA CYAN WHITE NORM

unset task docker_opts keep from_hsh
unset pre_ins pre_add post_ins post_add
for opt do
        shift
	arg=${opt#*=}
        case "$opt" in
		--task) task=$(awk '{print $1}' .git/.girar-build | tail -1) ;;
		--task=*) task=$arg ;;
		--hsh | --local) from_hsh=y ;;
		--no-cache) docker_opts+=" $opt" ;;
		--no-cache=*) docker_opts+=" --no-cache-filter=$arg" ;;
		--pre-install=*)      pre_ins=$arg ;;
		--pre-install-add=*)  pre_add=$arg ;;
		--post-install=*)     post_ins=$arg ;;
		--post-install-add=*) post_add=$arg ;;
		--keep) keep= ;;
		-*) fatal "unknown option: $opt" ;;
                *) fatal "unknown argument: $opt" ;;
        esac
done

pkgnames() { cut -f1 | sort -u | grep -Eve '-(debuginfo|checkinstall)' | xargs -r; }

update_install_lists() {
	local git_pre_ins git_pre_add git_post_ins git_post_add
	# Git config ci.pre-install overrides, ci.pre-install-add adds.
	git_pre_ins=$(git config --local --get ci.pre-install) &&
		pre_install=$git_pre_ins
	git_pre_add=$(git config --local --get ci.pre-install-add) &&
		pre_install+=" $git_pre_add"
	[ -v pre_ins ] &&
		pre_install="$pre_ins"
	[ -v pre_add ] &&
		pre_install+=" $pre_add"
	# Installs.
	git_post_ins=$(git config --local --get ci.post-install) &&
		install=" $git_post_ins"
	git_post_add=$(git config --local --get ci.post-install-add) &&
		install+=" $git_post_add"
	[ -v post_ins ] &&
		install="$post_ins"
	[ -v post_add ] &&
		install+=" $post_add"
	return 0
}

trap 'echo "$BRIGHT$RED❌ FAIL$NORM"' ERR
trap 'beep' EXIT

if [ -v from_hsh ]; then
	# Test local build, only authoritative records are in the build log.
	eval "$(hsh --printenv)"
	repo=$(grep -m1 -Po 'branch=\K\S*(?= target=)' log)
	pre_install=$(sed -En 's!^\S+ Wrote:\s/usr/src/RPM/RPMS/[[:graph:]/]+/(\S+)-[^-]+-alt\S+\.rpm\s.*!\1!p' log | pkgnames)
	install=$(sed -En 's!^\S+ Wrote:\s/usr/src/RPM/RPMS/[[:graph:]/]+/(\S+-[^-]+-alt\S+\.rpm)\s.*!/repo/\1!p' log | pkgnames)
	update_install_lists
	name="hsh.${pre_install%% *}"
	echo >&2 "+ docker run --name=$name ..."
	# shellcheck disable=SC2086,SC2154
	docker run ${keep---rm} \
		--name="$name" \
		-v "$def_repo/$HOSTTYPE/RPMS.hasher:/repo" \
		"alt:${repo:-sisyphus}" \
		bash -exc "
			apt-get update
			apt-get install -y $pre_install
			apt-get install -y $install
		"
	gear-checklist --update ci-upgrade-hsh
	# docker container ls -a
	if [ ! -v keep ]; then
		echo "🔴 To clear containers run: docker container prune -f"
	fi
elif [ -v task ]; then
	repo=$(curl -sSfL "https://git.altlinux.org/tasks/$task/task/repo")
	pre_install=$(curl -sSfL "https://git.altlinux.org/tasks/$task/plan/rm-bin" | pkgnames)
	update_install_lists
	install=$(curl -sSfL "https://git.altlinux.org/tasks/$task/plan/add-bin" | pkgnames)
	# Version to automatically invalidate Docker cache, apt-repo ignores that argument.
	version=$(curl -sSfL "https://git.altlinux.org/tasks/$task/task/version")

	echo >&2 "+ docker build -t task$task ..."
	# shellcheck disable=SC2086
	docker build ${docker_opts-} --progress=plain -t "task$task" -f - . <<-EOF
		FROM alt:$repo AS pre
		SHELL ["/bin/bash", "-xec"]
		RUN apt-get update && apt-get install -y apt-repo $pre_install
		FROM pre AS task
		RUN apt-repo add $task $version && apt-get update
		RUN apt-get install -y $install
	EOF
	gear-checklist --task="$task" ci-upgrade-task --skip=ci-upgrade-hsh
	# docker image ls
	if [ ! -v keep ]; then
		docker rmi "task$task"
		echo "$YELLOW🔴$NORM To clear caches run: docker builder prune -a -f"
	fi
else
	echo >&2 "User --task or --hsh"
	exit 1
fi
echo "$BRIGHT$GREEN✅ OK$NORM"
