#!/bin/bash
set -efu +o posix

if [ -t 1 ]; then
  BRIGHT=$'\e[1m'
     RED=$'\e[31m'
   GREEN=$'\e[32m'
  YELLOW=$'\e[33m'
    BLUE=$'\e[34m'
 MAGENTA=$'\e[35m'
    CYAN=$'\e[36m'
   WHITE=$'\e[37m'
    NORM=$'\e[m'
else
  BRIGHT='' RED='' GREEN='' YELLOW='' BLUE='' MAGENTA='' CYAN='' WHITE='' NORM=''
fi
export BRIGHT RED GREEN YELLOW BLUE MAGENTA CYAN WHITE NORM

fatal() { echo >&2 "${0##*/}: $*"; exit 1; }
topdir=$(git rev-parse --show-toplevel)
cd "$topdir"
cl=.git/checklists
mkdir -p "$cl"

mode=check
commit_head=@
unset task hasher skip
for o do
	shift
	arg=${o#*=}
        case "$o" in
		--list|-l) mode=list ;;
		--check)   mode=check ;;
		--update)  mode=update ;;
		--task=*)  mode=update; task=$arg ;;
		--skip=*)  skip+=("$arg") ;;
		--commit)   unset commit_head ;;
		--commit=*) commit_head=$arg ;;
		--*) fatal "Unknown option $o" ;;
		+*)        mode=update; set -- "$@" "${o#+}" ;;
		*-)        mode=update; skip+=("${o%-}") ;;
		*)  set -- "$@" "$o" ;;
	esac
done

if [[ -v commit_head ]]; then
	head_rev=$(git rev-parse "$commit_head")
else
	head_rev=$(git stash create)
fi
# prev_release=$(git describe --tags --match '*-alt*' --abbrev=0 @~)

check_ref() {
	local item=$1 ref=$2 desc; shift 2
	desc=$*
	local bright=$BRIGHT
	[[ $item == *- ]] && bright=
	if git diff --quiet "$head_rev" "$ref"; then
		echo -e "\t$bright${GREEN}YES${NORM}\t$item\t$desc"
	elif [[ $item == *- ]]; then
		echo -e "\t$bright${BLUE}SKIP${NORM}\t$item\t$desc"
	else
		echo -e "\t$bright${RED}NO${NORM}\t$item\t$desc"
		n=$(git diff --stat "$ref" "$head_rev" | wc -l)
		((n<5)) && git diff --stat "$ref" "$head_rev"
		return 1
	fi
}

shopt -s nullglob
if [[ $mode == check ]]; then
	ret=0
	set +f
	for i in "$cl/"*; do
		[[ $i == *~ ]] && continue
		t=$(tail -1 "$i")
		# shellcheck disable=SC2086
		check_ref "$(basename $i)" $t || ret=$?
	done
	exit $ret
elif [[ $mode == update ]]; then
	shopt -s lastpipe
	unset updated name
	if (( $# )); then
		name=$1
		shift
		ts=$(date --iso-8601=minutes)
		if [[ $name == *- ]]; then
			# Only skip, do nothing else.
			[[ -e $cl/${name%-} ]] && mv -n "$cl/${name%-}" "$cl/$name"
			unset name
			updated=y
		else
			# Return from skipped status.
			[[ -e $cl/$name- ]] && mv -n "$cl/$name-" "$cl/$name"
		fi
		if [ -v task ]; then
			declare -i count=0
			unset remote_rev
			curl -Y0 -LSsf "https://git.altlinux.org/tasks/$task/info.json" |
			grep -P -o '"tag_id": "\K[0-9a-z]+' |
			while read -r ref; do
				count+=1
				rev=$(git rev-parse "$ref^{commit}" 2>/dev/null || :)
				if [[ $head_rev == "$rev" ]]; then
					echo "$ref $ts $*" >> "$cl/$name"
					updated=y
					break
				elif [[ -n $rev ]]; then
					remote_rev=$rev
				fi
			done
			if [[ ! -v updated ]]; then
				echo "The ref[$count] from task $task is not HEAD in this repo."
				current_head=$(git rev-parse @)
				print_head=$head_rev
				[[ $head_rev == "$current_head" ]] && print_head=
				# shellcheck disable=SC2086
				[ -v remote_rev ] &&
				(set -x; git diff --stat "$remote_rev" $print_head)
				unset print_head
			fi
			unset count remote_rev
		elif [ -v name ]; then
			echo "$head_rev $ts $*" >> "$cl/$name"
			updated=y
		fi
	elif [ -v skip ]; then
		updated=y
	fi
	if [ -v updated ]; then
		for i in "${skip[@]}"; do
			[ -e "$cl/$i" ] && mv -n "$cl/$i" "$cl/$i-"
		done
		true
	else
		echo >&2 "$BRIGHT$RED! checklist is not updated$NORM"
		exit 1
	fi
else
	set +f
	for i in "$cl/"*[^~]; do
		ls -l "$i"
	done
fi
