#!/bin/bash
set -efu +o posix

unset pick pickopts
for o do
        shift
        case "$o" in
		-e|-s|-n|-m|-x|--no-ff|--ff) pickopts+=("$o") ;;
		--cherry-pick|--pick) pick=y ;;
		*) set -- "$@" "$o"
	esac
done

get_base() {
	local url=$1 owner repo

	if [[ $url =~ https://github.com/([^/]+)/(.*) ]]; then
		owner=${BASH_REMATCH[1]}
		repo=${BASH_REMATCH[2]}
		repo=${repo%.git}
	else
		echo >&2 "OWNER/REPO unknown."
		exit 1
	fi

	curl -sSLf "https://api.github.com/repos/$owner/$repo/pulls/$PR" \
		| jq -r .base.sha
}

PR=${1:?pull request id}
if [[ $PR =~ (https://github.com/.*/.*)/(pull/[[:digit:]]+) ]]; then
	url=${BASH_REMATCH[1]}
	pr=${BASH_REMATCH[2]}
	(set -x; git fetch "$url.git" "$pr/head")
elif [[ $PR =~ ^[[:digit:]]+$ ]]; then
	url=$(git remote get-url origin)
	(set -x; git fetch origin "pull/$PR/head")
else
	echo >&2 "Unknown URL format"
	exit 1
fi
if [ -v pick ]; then
	base=$(get_base "$url")
	git l "$base..FETCH_HEAD"
	gum confirm 'Pick?'
	(set -x; git cherry-pick "${pickopts[@]}" "$base..FETCH_HEAD")
fi
