#!/bin/bash
set -efu +o posix

unset pick pickopts
for o do
        shift
        case "$o" in
		-e|-s|-n|-m|-x|--no-ff|--ff) pickopts+=("$o") ;;
		--cherry-pick|--pick) pick=y ;;
		*) set -- "$@" "$o"
	esac
done

PR=${1:?pull request id}
if [[ $PR =~ (https://github.com/.*/.*)/(pull/[[:digit:]]+) ]]; then
	url=${BASH_REMATCH[1]}
	pr=${BASH_REMATCH[2]}
	(set -x; git fetch "$url.git" "$pr/head")
elif [[ $PR =~ ^[[:digit:]]+$ ]]; then
	(set -x; git fetch origin "pull/$PR/head")
else
	echo >&2 "Unknown URL format"
	exit 1
fi
if [ -v pick ]; then
	git l ..FETCH_HEAD
	gum confirm 'Pick?'
	(set -x; git cherry-pick "${pickopts[@]}" ..FETCH_HEAD)
fi
