#!/bin/bash -efu
# Add gears remote (c) vt

V() {
        printf >&2 "\e[1;33m%s" "$PS4"
        printf >&2 ' %q' "$@"
        printf >&2 '\e[m\n'
        "$@"
}

description="$(gear --describe --disable-specsubst ${commit:+-t "$commit"})"
name="${description%% *}"

url="gitery:/gears/${name:0:1}/$name.git"

if git remote | grep -qxF 'gears'; then
	git remote set-url 'gears' "$url"
else
	git remote add 'gears' "$url"
fi
V git fetch 'gears'

br=$(git branch --show-current)

if git diff --quiet &&
   git diff --quiet --cached; then
	echo >&2 "Work tree of $br is clean."
else
	echo >&2 "Work tree of $br is unclean, aborting."
	exit 1
fi

if ! git show-ref -q "gears/$br"; then
	echo >&2 "$br does not exist on gears remote, aborting."
	exit 1
fi
git branch -q --set-upstream-to="gears/$br" "$br"
V git branch -vv
if git merge-base --is-ancestor HEAD gears/$br; then
	V git pull --rebase
fi
