#!/bin/bash
# List built packages for the repo we are in
set -eu +o posix

allow_debuginfo=
allow_checkinstall=
invert_match=0
allow_all=
show_srpm=
unset tag target
for o do
        shift
        case "$o" in
		-a|--all)       allow_all=y ;;
		--src)          show_srpm=y ;;
		--debuginfo)    allow_debuginfo=y ;;
		--checkinstall) allow_checkinstall=y ;;
		-32)            target=i586 ;;
		--target=*)     target=${o#*=} ;;
		--*)            tag=${o#--} ;;
		-v)             invert_match=1 ;;
		*) set -- "$@" "$o"
	esac
done

# shellcheck disable=SC2183,SC2046
srcrpm=$(printf '%s-%s-%s.src.rpm' $(gear --describe --disable-specsubst))

eval "$(hsh --printenv | grep -e '^def_repo=' -e '^workdir=' -e '^def_target=')"

# shellcheck disable=SC2154
if [ -n "$show_srpm" ]; then
	cd "$def_repo/SRPMS.hasher"
else
	[ -v target ] || target=${def_target-}
	cd "$def_repo/${target:-$(arch)}/RPMS.hasher"
fi

shopt -s nullglob
for i in *.rpm; do
	if [ -n "$show_srpm" ]; then
		[ "$srcrpm" = "$(basename "$i")" ] || continue
	else
		SOURCERPM=$(rpm -qp --qf '%{SOURCERPM}' "$i")
		[ "$srcrpm" = "$SOURCERPM" ] || continue
		if [ -z "$allow_all" ]; then
			[ -n "$allow_checkinstall" ] || [[ $i != *-checkinstall-* ]] || continue
			[ -n "$allow_debuginfo" ]    || [[ $i != *-debuginfo-* ]]    || continue
		fi
		if (( $# )); then
			match=$invert_match
			for m in "$@"; do
				[[ $i =~ $m ]] && match=$((match ^ 1))
			done
			(( match )) || continue
		fi
	fi
	if [ -v tag ]; then
		q=$(sed -E 's/\w+/%{&}/g' <<< "$tag")
		rpmquery --qf "$q\n" -p "$i"
	else
		printf "%s/%s\n" "$PWD" "$i"
	fi
done

