#!/bin/bash -efu

gear_describe() {
	set -- $(gear --describe --commit)
	export name=$1 version=$2 release=$3
}
gear_describe

if [[ $name == kernel-image-* ]]; then
	toplevel=$(git rev-parse --show-toplevel)
	kernel_src_version=$(grep -Po 'kernel_src_version\s+\K\S+' "$toplevel/kernel-image.spec")
	builddir="$name-$version-$release/kernel-source-$kernel_src_version"
else
	builddir="$name-$version"
fi

untar_opts=()
untar_verb=vv
for opt; do
	shift
	case "$opt" in
		-q) untar_verb= ;;
		--*) untar_opts+=("$opt") ;;
		*) set -- "$@" "$opt"
	esac
done

prefix=$(git rev-parse --show-prefix)
{
	set -o pipefail
	hsh-run -- bash -c "$(cat)" |
		tar x${untar_verb}f - "${untar_opts[@]}"
} <<EOF
	set -e
	cd /usr/src/RPM/BUILD/"$builddir"
	cd kernel-source-* 2>/dev/null ||:
	cd ./"$prefix"
	tar cf - $*
EOF
