#!/bin/bash
# List built packages for the repo we are in
set -eu +o posix

allow_debuginfo=
allow_checkinstall=
invert_match=0
allow_all=
show_srpm=
unset tag target repo today
for o do
        shift
        case "$o" in
		-a|--all)       allow_all=y ;;
		--src)          show_srpm=y ;;
		--debuginfo)    allow_debuginfo=y ;;
		--checkinstall) allow_checkinstall=y ;;
		-32)            target=i586 ;;
		--target=*)     target=${o#*=} ;;
		--repo)         repo=Sisyphus ;;
		--repo=*)       repo=${o#*=} ;;
		--pub|--ftp)    today=y ;;
		--*)            tag=${o#--} ;;
		-v)             invert_match=1 ;;
		*) set -- "$@" "$o"
	esac
done

eval "$(hsh --printenv | grep -e '^def_repo=' -e '^workdir=' -e '^def_target=')"
[ -v target ] || target=${def_target-}

read -r name version release <<<"$(gear --describe --disable-specsubst)"
srcrpm="$name-$version-$release.src.rpm"

list=()
shopt -s nullglob
# shellcheck disable=SC2154
if [ -v repo ]; then
	read -r name _ <<<"$(gear --describe --disable-specsubst)"
	[ -v today ] && repo_base="/mnt/space/pub/distributions/ALTLinux/$repo" || repo_base="/ALT/$repo"
	repo_srpm=$(ugrep -z -P "^\Q$name\E\t" "$repo_base/files/list/src.list.xz" | awk '{print $3}')
	if [ -n "$show_srpm" ]; then
		list=("$repo_base/files/SRPMS/$repo_srpm")
	else
		shopt -s lastpipe
		ugrep -z -F "$repo_srpm" "$repo_base/files/list/bin.list.xz" |
		awk -v srpm="$repo_srpm" '$5 == srpm' |
			while read -r _ _ ar bp _; do
				[[ $ar == @(noarch|$target) ]] || continue
				list+=("$repo_base/files/$ar/RPMS/$bp")
			done
	fi
elif [ -n "$show_srpm" ]; then
	list=("$def_repo/SRPMS.hasher/$srcrpm")
else
	cd "$def_repo/${target:-$(arch)}/RPMS.hasher"
	for i in *.rpm; do
		SOURCERPM=$(rpm -qp --qf '%{SOURCERPM}' "$i")
		[ "$srcrpm" = "$SOURCERPM" ] || continue
		list+=("$def_repo/${target:-$(arch)}/RPMS.hasher/$i")
	done
fi

for i in "${list[@]}"; do
	if [ -z "$allow_all" ]; then
		[ -n "$allow_checkinstall" ] || [[ $i != *-checkinstall-* ]] || continue
		[ -n "$allow_debuginfo" ]    || [[ $i != *-debuginfo-* ]]    || continue
	fi
	if (( $# )); then
		match=$invert_match
		for m in "$@"; do
			[[ $i =~ $m ]] && match=$((match ^ 1))
		done
		(( match )) || continue
	fi
	if [ -v tag ]; then
		q=$(sed -E 's/\w+/%{&}/g' <<< "$tag")
		rpmquery --qf "$q\n" -p "$i"
	else
		printf "%s\n" "$i"
	fi
done

