#!/bin/bash
set -efu +o posix

cd "$HOME/src/kernel-image"
list_branches() {
	local format="${1-}%(refname)"
	git branch -r --sort=-committerdate --format="$format" |
		grep '\brefs/remotes/gears/' |
		grep -v '\brefs/remotes/gears/source-' |
		grep -v '\brefs/remotes/gears/.*/HEAD' |
		sed 's!\brefs/remotes/!!'
}

pathspec=( "config*" )
unset show_unmatched show_tag
for o do
	shift
	case "$o" in
		--help)
			echo >&2 "Use git log options such as -G / --shortstat / --numstat"
			exit 1
			;;
		-l|--list) list_branches '%(creatordate:short) '; exit ;;
		--spec) pathspec=( 'kernel-image.spec' ) ;;
		--pathspec=*)
			# shellcheck disable=SC2206
			pathspec=( ${o#*=} )
			;;
		--show-no-match) show_unmatched=y ;;
		--tag) show_tag=y ;;
		*) set -- "$@" "$o"
	esac
done

if [[ $* == [A-Z]* ]]; then
	echo >&2 "Error: Perhaps, run: $(basename "$0") -G'$*'"
	exit 1
fi

echo >&2 ":: git log $* -- ${pathspec[*]}"
while read -r br; do
	printf -v prefix '%-30s ' "${br#gears/}"
	if [ -v show_tag ]; then
		tag=$(git tag --points-at "$br" 'kernel-image-*' | head -1)
		tag=${tag#kernel-image-}
		tag=${tag%%-alt*}
		printf -v tag '%-20s' "[$tag]"
		prefix+="$tag "
	fi
	if git log --oneline --format='%h %cd - %s (%an)' --date=short "$@" "$br" -- "${pathspec[@]}" | grep .; then
		:
	elif [ -v show_unmatched ]; then
		echo "No match"
	fi | sed "s!^!$prefix!"
done < <(list_branches)

