#!/bin/bash
set -efu +o posix

cd "$HOME/src/kernel-image"
list_branches() {
	local format="${1-}%(refname)"
	git branch -r --sort=-committerdate --format="$format" |
		grep '\brefs/remotes/gears/' |
		grep -v '\brefs/remotes/gears/source-' |
		sed 's!\brefs/remotes/!!'
}

pathspec=( "config*" )
for o do
	shift
	case "$o" in
		--help)
			echo >&2 "Use git log options such as -G / --shortstat / --numstat"
			exit 1
			;;
		-l|--list) list_branches '%(creatordate:short) '; exit ;;
		--pathspec=*)
			# shellcheck disable=SC2206
			pathspec=( ${o#*=} )
			;;
		*) set -- "$@" "$o"
	esac
done

if [[ $* == [A-Z]* ]]; then
	echo >&2 "Error: Perhaps, run: $(basename "$0") -G'$*'"
	exit 1
fi

echo >&2 ":: git log $* -- ${pathspec[*]}"
while read -r br; do
	printf -v prefix '%-30s ' "${br#gears/}"
	git log --oneline --format='%h %cd - %s (%an)' --date=short "$@" "$br" -- "${pathspec[@]}" | grep . | sed "s!^!$prefix!"
done < <(list_branches)

