#!/bin/bash -eu

show_file=
if [ -e "${1-}" ]; then
	file=$1
else
	branch=Sisyphus
	arch=x86_64
	flavour=std-def
	for i; do
		ok=
		if [ -d /ALT/$i ]; then
			branch=$i
		elif [ -d /ALT/$branch/files/$i ]; then
			arch=$i
		elif [ -e /ALT/$branch/files/$arch/RPMS/kernel-image-$i-[1-9]*.rpm ]; then
			flavour=$i
		elif [ "$i" = --file ]; then
			show_file=only
		else
			echo >&2 "Unknwon package selector: $i"
			exit 2
		fi
	done
	set +f
	file=( /ALT/$branch/files/$arch/RPMS/kernel-image-$flavour-[1-9]*.$arch.rpm )
	set -f
fi

if [ -n "$show_file" ]; then
	echo "$file"
else
	[ -t 1 ] && echo >&2 $file
	rpmpeek $file bash -c 'cat boot/config-*' 2>/dev/null
fi
