#!/bin/bash

set -efu
shopt -s extglob
V() { echo -e "+ \e[1;33m$@\e[m" >&2; "$@"; }

unset shared usertask deps disapprove
force=
kmodules=y
runthetask=y
commit=--test-only
kernelbot=y
unset push_branch unset_push_branch
for opt do
	shift
	case "$opt" in
		--gitery) unset kernelbot ;;
		--kernelbot) kernelbot=y ;;
		-f | --force) force="-f" ;;
		--task=*) usertask="${opt#*=}" ;;
		--commit) commit=--commit kernelbot=y ;;
		--share*) shared=y ;;
		--repo=* | --branch=*) branch="${opt#*=}" ;;
		--no-kmodules) unset kmodules ;;
		--no-run) unset runthetask ;;
		--disapprove) disapprove=y ;;
		--branch) push_branch=y ;;
		--no-branch) unset_push_branch=y ;;
		--test) disapprove=y; unset_push_branch=y ;;
		--deps=*) deps="${opt#*=}" ;;
		*) set -- "$opt" "$@"; break ;; # tags
	esac
done

if [ -v kernelbot ]; then
	remote=kernelbot
	repo=/people/kernelbot/packages/kernel-image
	approver=girarbot
	push_branch=y
	girar=girarbot
else
	remote=gitery
	repo=kernel-image
	approver=girar
	girar=girar
fi
[ -v unset_push_branch ] && unset push_branch

br=$(git branch --show-current)
[ -n "${branch-}" ] || branch=${br#*/}
case $branch in
	sisyphus | [cp][1-9]* | icarus* ) ;;
	*) echo >&2 "Invalid repo $branch"; exit 1 ;;
esac
brflvr=${br%/*}
case $brflvr in
	un-def|std-def|std-pae|std-debug|std-next|un-next|next|rt|+([[:digit:]]).+([[:digit:]])) ;;
	kasan)
		commit=--test-only
		unset push_branch
		unset kmodules
		;;
	*) echo >&2 "Invalid flavour $brflvr"; exit 1 ;;
esac

if [ -v push_branch -o -v kmodules ]; then
	tests=$(git log --oneline --author=altlinux -i --grep=test "$remote/$br..")
	if [ -n "$tests" ]; then
		echo "$tests" | sed 's/^/\t(test) /'
		echo >&2 "Test build, do not push branch, do not add kmodules."
		unset push_branch
		unset kmodules
	fi
fi

# Set tags to build.
if [ "$*" ]; then
	set "$@"
else
	set -- $(git tag --points-at @)
fi
[ -v push_branch ] && V git push $remote $br $force
if [ $# -eq 0 ]; then
	echo >&2 "No tags. Run kernel-tag?"
	exit 1
fi
for tag; do
	flavour=${tag#kernel-image-}
	flavour=${flavour%-*-alt*}

	V git push $remote $tag $force
	if [ -v usertask ]; then
		task=$usertask
	else
		task=$(V ssh -n $girar task new $branch)
	fi
	V ssh -n $girar task add $task repo $repo $tag
	[ -v shared ] && V ssh -n $girar task share $task enable
	if [ -v kmodules ] && V ssh -n $girar task add $task kmodules $flavour; then
		msg="-m kmodules:$tag"
	else
		msg=
	fi
	case $branch in
		sisyphus) subtask=100 ;;
		*)	  subtask=all ;;
	esac
	if [ -v disapprove ]; then
		echo TEST | V ssh $girar task disapprove $task $subtask
	else
		echo PESIGN | V ssh $approver task approve $task $subtask
	fi
	if [ -v deps ]; then
		V ssh -n $girar task deps $task add "$deps"
	fi
	runcmd="ssh -n $girar task run --fail-late $commit $task $msg"
	if [ -v runthetask ]; then
		V $runcmd
	else
		echo -e "To run: \e[1;35m$runcmd\e[m"
		unset task
	fi
done

[ -z "$task" ] || exec task-tail "$task"
