#!/bin/bash -efu

V() { echo "- $*" >&2; "$@"; }

if [ -n "$*" ]; then
	fvnew="$*"
else
	br=$(git branch --show-current)
	branch=${br#*/}
	brflvr=${br%/*}
	case $branch in
		sisyphus|p[1-9]*|c[1-9]*) ;;
		*) echo >&2 "Invalid repo $branch"; exit 1 ;;
	esac
	case $brflvr in
		un-def|std-def|std-pae|std-debug|next) ;;
		*) echo >&2 "Invalid flavour $brflvr"; exit 1 ;;
	esac
	fvnew=$brflvr
fi
fvold=$(git config gear.specsubst.kflavour)
if [ "$fvold" = "$fvnew" ]; then
	echo >&2 "Flavour is already $fvold"
else
	echo >&2 "Changing flavour $fvold -> $fvnew"
	git config gear.specsubst.kflavour "$fvnew"
fi
