#!/bin/bash

export GREP_COLORS="mt=01;32"
set -eu +f -o pipefail
rroot=/mnt/space/mirror
skip="5.1|c[678].*|c9[fm]1|c9m2|c9f1|p[5678]|.*armh"
skip="5.1|c[678].*|fm]1|c9m[12]|c9f1|p[567]|.*armh"

package=kernel-image
branch=Sisyphus arch=x86_64 flavour=std-def
branches= flavours= arches=
configs= pattern= all_arch=
unset logs
for i; do
	[ "$i" = sisyphus ] && i=Sisyphus
	[ "$i" = s ] && i=Sisyphus
	[ "$i" = def ] && flavours+=" std-def un-def std-pae std-debug"
	if [ -d "/ALT/$i" ]; then
		branch=$i
		branches+=" $i"
		continue
	fi
	if [ -d "/ALT/$branch/files/$i" ]; then
		arch=$i
		arches+=" $i"
		continue
	fi
	case $i in
		std-def|std-debug|std-pae|un-def|rt|kvm|std-kvm|xenomai|centos|ovz-el|ovz-el7|mp)
			flavours+=" $i"
			continue
			;;
	esac
	if ls "/ALT/$branch/files/*/RPMS/$package-$i-[1-9]*.rpm" &>/dev/null; then
		flavour=$i
		flavours+=" $i"
		continue
	fi
	case "$i" in
		--package=*) package="${i#*=}" ;;
		--config*) configs=y ;;
		--grep=*)  pattern="${i#*=}"; configs=y ;;
		--all-arch*) all_arch=y ;;
		--log*) logs=y ;;
		-*) echo "No option $i"; exit 1 ;;
	esac
done

[ -z "${branches-}" ] && branches=$(cd $rroot; ls | grep -E -vwe "$skip")
: ${flavours:=*}
[ -z "$arches" ] && arches=$arch

# echo "branches: $branches"
# echo "flavours: $flavours"

set -f
list=
for b in $branches; do
	for f in $flavours; do
		if [ -n "$all_arch" ]; then
			arches=$(ls $rroot/$b/files/ | grep -v -e - -e SRPMS -e list)
		fi
		for a in $arches; do
			r=$rroot/$b/files/$a/RPMS
			test -d $r || continue
			pat=$r/$package-$f-[0-9]*-alt*.$a.rpm
			set +f
			for i in $pat; do
				test -e $i || continue
				flv=${i##*"$package"-}
				flv=${flv%%-[0-9]*}
				[[ $flv =~ debuginfo|domU|checkinstall ]] && continue
				list+=" $i"
			done
			set -f
		done
	done
done
if [ "$configs" ]; then
	trap "kill $$" INT
	list=$(echo $list | tr ' ' '\n' | sort)
	for i in $list; do
		prefix=${i##*mirror/}
		branch=${prefix%%/files/*}
		prefix=$package-${prefix##*"$package"-}
		prefix=${prefix%.rpm}
		if [ -n "$pattern" ]; then
			if ! kernel-config $i | sed "s,^,$branch/$prefix:," | grep --color=auto "$pattern"; then
				echo "$branch/$prefix:no match"
			fi
		else
			kernel-config $i | sed "s,^,$branch/$prefix:,"
		fi
	done
	exit
fi
if [ -v logs ]; then
	list=$(echo $list | tr ' ' '\n' | sort)
	# https://git.altlinux.org/tasks/309028/build/100/x86_64/log
	for rpm in $list; do
		DISTTAG=$(rpm -qp --qf "%{DISTTAG}" "$rpm")
		try=${DISTTAG#*+}
		task=${try%%.*}
		subtask=${try#"$task".}
		subtask=${subtask%%.*}
		{
			echo : $i task=$task subtask=$subtask arch=$arch
			curl -sS -L -f "https://git.altlinux.org/tasks/$task/build/$subtask/$arch/log"
		} | less -K || exit
	done
	exit
fi
if [ -t 1 ]; then
	HIGHLIGHT=$'sed -E s!/([Ss]isyphus)/!/\e[1;33m\\1\e[m/!'
else
	HIGHLIGHT=cat
fi

ls -ltrd -- $list \
	| sed -E 's/^\S+\s+\S+\s+\S+\s+\S+//' \
	| $HIGHLIGHT \
	| grep -E --color '^|[0-9.]+-alt[^.]+'

