#!/bin/bash

set -eu +f
rroot=/mnt/space/mirror
skip="5.1|c[678].*|c9[fm]1|c9m2|p[5678]|.*armh"
skip="5.1|c[678].*|fm]1|p[567]|.*armh"

branch=Sisyphus arch=x86_64 flavour=std-def
branches= flavours= arches=
configs= pattern= all_arch=
for i; do
	if [ -d /ALT/$i ]; then
		branch=$i
		branches+=" $i"
		continue
	fi
	if [ -d /ALT/$branch/files/$i ]; then
		arch=$i
		arches+=" $i"
		continue
	fi
	if ls /ALT/$branch/files/*/RPMS/kernel-image-$i-[1-9]*.rpm &>/dev/null; then
		flavour=$i
		flavours+=" $i"
		continue
	fi
	case "$i" in
		--config*) configs=y ;;
		--grep=*)  pattern="${i#*=}" ;;
		--all-arch*) all_arch=y ;;
	esac
done

[ -z "${branches-}" ] && branches=$(cd $rroot; ls | grep -E -vwe "$skip")
: ${flavours:=*}
[ -z "$arches" ] && arches=$arch

# echo "branches: $branches"
# echo "flavours: $flavours"

set -f
list=
for b in $branches; do
	for f in $flavours; do
		if [ -n "$all_arch" ]; then
			arches=$(ls $rroot/$b/files/ | grep -v -e - -e SRPMS -e list)
		fi
		for a in $arches; do
			r=$rroot/$b/files/$a/RPMS
			test -d $r || continue
			pat=$r/kernel-image-$f-[0-9]*-alt*.$a.rpm
			set +f
			for i in $pat; do
				test -e $i || continue
				flv=${i##*kernel-image-}
				flv=${flv%%-[0-9]*}
				[[ $flv =~ debuginfo|domU|checkinstall ]] && continue
				list+=" $i"
			done
			set -f
		done
	done
done
if [ "$configs" ]; then
	list=$(echo $list | tr ' ' '\n' | sort)
	for i in $list; do
		prefix=${i##*mirror/}
		branch=${prefix%%/files/*}
		prefix=kernel-image-${prefix##*kernel-image-}
		prefix=${prefix%.rpm}
		if [ -n "$pattern" ]; then
			if ! kernel-config $i | sed "s,^,$branch/$prefix:," | grep --color=auto $pattern; then
				echo "$branch/$prefix:no match"
			fi
		else
			kernel-config $i | sed "s,^,$branch/$prefix:,"
		fi
	done
	exit
fi
ls -ltrd -- $list \
	| sed -E 's/^\S+\s+\S+\s+\S+\s+\S+//' \
	| grep -E --color '^|[0-9.]+-alt[^.]+'

