#!/bin/bash -eu

rroot=/mnt/space/mirror
skip="5.1|c[678].*|c9[fm]1|c9m2|p[5678]|.*armh"
skip="5.1|c[678].*|fm]1|p[567]|.*armh"

branch=Sisyphus arch=x86_64 flavour=std-def
branches= flavours=
for i; do
	if [ -d /ALT/$i ]; then
		branch=$i
		branches+=" $i"
	fi
	if [ -d /ALT/$branch/files/$i ]; then
		arch=$i
	fi
	if [ -e /ALT/$branch/files/$arch/RPMS/kernel-image-$i-[1-9]*.rpm ]; then
		flavour=$i
		flavours+=" $i"
	fi
done

[ -z "${branches-}" ] && branches=$(cd $rroot; ls | grep -E -vwe "$skip")
: ${flavours:=*}

# echo "branches: $branches"
# echo "flavours: $flavours"

set -f
list=
for b in $branches; do
	for f in $flavours; do
		r=$rroot/$b/files/$arch/RPMS
		test -d $r || continue
		f=$r/kernel-image-$f-[0-9]*-alt*.*.rpm
		set +f
		for i in $f; do
			test -e $i || continue
			flv=${i##*kernel-image-}
			flv=${flv%%-[0-9]*}
			[[ $flv =~ debuginfo|domU|checkinstall ]] && continue
			list+=" $i"
		done
		set -f
	done
done
ls -ltrd -- $list \
	| sed -E 's/^\S+\s+\S+\s+\S+\s+\S+//' \
	| grep -E --color '^|[0-9.]+-alt[^.]+'

