#!/usr/bin/ruby -Kn
# SPDX-License-Identifier: CC0
# Another simple log diff tool

require 'tmpdir'
require 'fileutils'

@s = [
  [/[\t ]+/, ' '],
  [/ -fdiagnostics-color=always/, ''],
  [/\033\[[0-9;]*[a-zA-Z]/, ''],
  [%r{/usr/src/tmp/rpm-tmp\.\S{4,6}}, '/usr/src/tmp/rpm-tmp.X'],
  [%r{/usr/src/tmp/\S{8}\.ltrans\d\.ltrans.o}, '/usr/src/tmp/X.ltrans0.ltrans.o'],
  [%r{/usr/src/tmp/vm\.\S{10}}, '/usr/src/tmp/vm.X'],
  [%r{\b0x[0-9a-f]+\b}, '0x0'],
  [/\d+/, '0'],
  [/^\[?0:0:0\]? /, ''],
  [/\^~+/, '^~'],
  [%r{\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b}, 'Jan'],
  [%r{\b(Sun|Mon|Tue|Wed|Thu|Fri|Sat)\b}, 'Sun'],
  [%r{/usr/bin/(sed|grep|mkdir|dd|bzip0|gzip|install|tar|cat|chgrp|chmod|chown|cp|cpio|mv|rm)\b}, '/bin/\1'],
  [%r{/bin/install\b}, '/usr/bin/ginstall'],
  [%r{w0\.[lgx]zdio\b}, 'w0.lzdio'],
]

class String
  def ggsub(repls)
    res = self.dup
    repls.each do |re, s|
      res.gsub!(re, s)
    end
    res
  end
end

@temp_dir = Dir.mktmpdir
at_exit do
  FileUtils.remove_entry(@temp_dir)
end

def mut(fa)
  a = IO.readlines(fa)
  ar = a.map {|e| e.ggsub(@s)}
  at = File.join(@temp_dir, File.basename(fa))
  File.write(at, ar.join)
  [at, a]
end

at, a = mut(ARGV.shift)
bt, b = mut(ARGV.shift)

header = true
acnt = bcnt = 0
diff_output = IO.popen(["diff", "-u", at, bt]) do |io|
  io.each_line do |line|
    if !header
      case line
      when /^-/
        printf '-%s', a[acnt - 1]
        acnt += 1
      when /^\+/
        printf '+%s', b[bcnt - 1]
        bcnt += 1
      when /^ /
        printf ' %s', b[bcnt - 1]
        acnt += 1
        bcnt += 1
      when /^@/
        header = true
      end
    end
    if header
      printf '%s', line
      case line
      when /^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/
        acnt = $1.to_i
        bcnt = $2.to_i
        header = false
      end
    end
  end
end
