#!/bin/bash
# Requires to be set in advance (per repo):
#   git config core.logAllRefUpdates always
set -efu
shopt -s lastpipe
toplevel=$(git rev-parse --show-toplevel)
cd "$toplevel"
if (($#)); then
	for refs in tags heads; do
		if [[ -f ".git/logs/refs/$refs/$1" ]]; then
			ref=$1
			refs=tags
			shift
			break
		fi
	done
else
	ref=$(git tag --points-at @)
	refs=tags
	if [[ -z $ref ]]; then
		ref=$(git branch --show-current)
		refs=heads
	fi
fi
commit_resolve() {
	local tag headref
	headref=$(git rev-parse @)
	tag=$(git tag --points-at "$1")
	if [[ -n $tag ]]; then
		echo "$tag"
	elif [[ $1 == "$headref" ]]; then
		echo "@"
	else
		echo "$1"
	fi
}

log=".git/logs/refs/$refs/$ref"
tac "$log" | while read -r a b c; do
	if [[ $a == 0000000000000000000000000000000000000000 ]]; then
		continue
	fi
	if [[ $c =~ \>[[:space:]]([[:digit:]]+)[[:space:]]\+[[:digit:]]{4}[[:space:]] ]]; then
		t=${BASH_REMATCH[1]}
		d=$(date -d "@$t" "+%Y-%m-%d")
		c=${c/$t/$d}
	fi
	echo '┌─────────────────────────────────────────────'
	echo "│ $c"
	if git diff --quiet "$a" "$b"; then
		# No difference
		(set -x; git -P l --color=always "$a...$b")
		echo
	else
		a=$(commit_resolve "$a")
		b=$(commit_resolve "$b")
		(set -x; git -P diff --color=always -p --stat "$@" "$a" "$b")
	fi
done |& less
