#!/bin/bash

set -efu -o pipefail

gear_describe()
{
	set -- $(gear --describe --commit 2>/dev/null)
	NAME=$1
	VERSION=$2
	RELEASE=$3
}

gear_describe

eval "$(hsh --printenv | grep -e '^def_repo=' -e '^workdir=')"
cd  "$def_repo/${def_target:-$(arch)}/RPMS.hasher"

list=()
for i in $(set +f; echo *.rpm); do
	SOURCERPM=$(rpm -qp --qf '%{SOURCERPM}' "$i")
	SRCNAME=${SOURCERPM%-*-*}
	SRCVREL=${SOURCERPM%.*.*}
	[ "$NAME-$VERSION-$RELEASE" = "$SRCVREL" ] || continue
	list+=( "$i" )
done

tmp=$(mktemp -d)
trap "rm -rf $tmp" 0
export QUOTING_STYLE=shell-escape
sep=

[ "$#" -eq 0 ] && echo "Default comparison is -R (--requires)"

shopt -s extglob
for i in "${list[@]}"; do
	name=${i%-*-*}
	printf "%s= %s =\n" "$sep" "$name"
	rpmvrel=${i%.*.*}
	rpmarch=${i#"$rpmvrel"}

	rpm -qp "$i" ${@:--R} > $tmp/$i
	touch -r "$i" $tmp/$i

	r=$(set +f; ls /ALT/sisyphus/files/*/RPMS/$name-+([^-])-+([^-])$rpmarch 2>/dev/null ||:)
	if [ -e "$r" ]; then
		rr=$(basename $r)
		rpm -qp "$r" ${@:--R} > $tmp/$rr
		touch -r "$r" $tmp/$rr
	else
		rr=/dev/null
	fi
	if [ -v STRIP ] && [ -s $tmp/$rr ]; then
		sed -i "s!$STRIP!!g" $tmp/$rr
	fi
	(
		cd $tmp
		${DIFF-colordiff -u} "$rr" "$i"  | sed 's/^/\t/' || :
	)
	sep=$'\n'
done
