#!/bin/bash
set -efu -o pipefail

task=${1?task-id}; shift
[[ $# -eq 0 ]] && set -- ''

unset skip
declare -i prev_id=0
while IFS=:= read -r a b c; do
	[[ $a == "id" ]] && continue
	declare -i id=a
	(( prev_id != id )) && unset dir tag_name delete package skip
	[[ -v skip ]] && continue
	prev_id=id
	case "$b" in
		dir | tag_name | rebuild_from | delete | package)
			declare "$b=$c"
			;;
	esac
	if [[ -v delete ]] && [[ -v package ]]; then
		printf 'del %s\n' "$package"
		skip=
	elif [[ -v dir ]] && [[ -v tag_name ]]; then
		printf '%s=%s\n' "$dir" "$tag_name"
		skip=
	fi
done < <(ssh -n girar task show "$task") | sed "$@"

